language: python

matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true

script:
    - pytest
    - pylint ping/*.py

before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame

install:
    - pipenv install

pipenv:
    system_site_packages: true
