language: python

matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true

services:
    - xvfb

script:
    - pytest
    - pylint ping/*.py
    - xvfb-run make test
    - xvfb-run --server-args="-screen 0 1024x768x24" make test

before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame

install:
    - pipenv install

pipenv:
    system_site_packages: true
