language: python

python:
    - "3.7"

script:
    - pytest
    - pylint ping/*

before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq python-pygame

install:
    - pipenv install

pipenv:
    system_site_packages: true
